application: ghelobytes-cloudsherpas
version: 1
runtime: php
api_version: 1

handlers:
- url: /
  upload: static/index.html
  static_files: static/index.html

- url: /js
  static_dir: static/js

- url: /api/.*
  script: server.php